version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      #- 3000:3000
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
