services:
  modsec2-nginx:
    container_name: nginx-security
    image: owasp/modsecurity-crs:3.3.5-nginx-202308071108
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./modsecurity.conf:/etc/modsecurity.d/modsecurity.conf
      - ./setup.conf:/etc/nginx/modsecurity.d/setup.conf
      - ./request-test.conf:/opt/modsecurity/rules/{before,after}-crs/request-test.conf
